# Generated by Django 5.1.6 on 2026-07-23 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0038_alter_otp_code_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 23, 22, 15, 19, 828355, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضای کد",
            ),
        ),
    ]
