# Generated by Django 5.1.6 on 2026-08-03 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0039_alter_otp_code_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 8, 3, 20, 12, 22, 30310, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضای کد",
            ),
        ),
    ]
