# Generated by Django 5.1.6 on 2026-08-04 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_alter_otp_code_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code_expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 8, 4, 20, 48, 55, 669770, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضای کد",
            ),
        ),
    ]
