# Generated by Django 5.1.6 on 2026-08-14 17:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0045_alter_otp_code_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code_expiry",
            field=models.DateTimeField(
                default=account.models.otp_expiry, verbose_name="تاریخ انقضای کد"
            ),
        ),
    ]
