# Generated by Django 5.1.6 on 2026-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_banner_pformance_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="text_about_us",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن درباره ما بخش فوتر"
            ),
        ),
    ]
