# Generated by Django 5.1.6 on 2026-07-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_sitesettings_text_about_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="تصویر"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="متن درباره ما"
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
            },
        ),
        migrations.DeleteModel(
            name="About_Me",
        ),
    ]
