# Generated by Django 5.1.6 on 2026-07-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_aboutme_delete_about_me"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="email1",
            new_name="email",
        ),
    ]
