# Generated by Django 5.1.6 on 2026-07-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_email1_sitesettings_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contactus",
            name="last_name",
        ),
        migrations.AddField(
            model_name="contactus",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام و نام خانوادگی"
            ),
        ),
    ]
