"""
Django settings for Shop project.
Generated by 'django-admin startproject' using Django 5.2.3.

"""

from django.apps import AppConfig
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent
import locale
import sys

if sys.platform.startswith("win32"):
    locale.setlocale(locale.LC_ALL, "Persian_Iran.UTF-8")
else:
    locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")


# Build paths inside the project like this: BASE_DIR / 'subdir'.


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-jmnsi&wpjdl^7o7qo$!vvpy4s9cv(&q82xj_-*pm^8&c5b!gbt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = "includes/welcome.html"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # jalali_date
    "jalali_date",
    # My_app
    "Products.apps.ProductsConfig",
    "account.apps.AccountConfig",
    "Social.apps.SocialConfig",
    "core.apps.CoreConfig",
    "Dashbord.apps.DashbordConfig",
    "Cart.apps.CartConfig",
    "order.apps.OrderConfig",
    "pyment.apps.PymentConfig",
    # Persian_app
    "admin_persian",
    # libray
    "django_social_share",
    "django_ckeditor_5",
    "ckeditor_uploader",  # uplod file and image
    "colorfield",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'utm_tracker.middleware.UtmTrackerMiddleware',
]

ROOT_URLCONF = "Shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / "Cart" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "context_processors.context_processors.Categories",
                "context_processors.context_processors.site_settings",
                "context_processors.context_processors.Banners",
                "context_processors.context_processors.brands",
                "context_processors.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "Shop.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "fa-ir"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


STATIC_URL = "statics/"
MEDIA_URL = "media/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "statics")]
MEDIA_ROOT = os.path.join("media")


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "account.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "account.authentication.EmailAuthBackend",
]

""" save session param utm """
UTM_TRACKER_SAVE_IN_SESSION = True

"""save in databases utm """
UTM_TRACKER_SAVE_IN_DB = True

"""ساختار UTM_PARAMS:
{
    'campaign_key': {
        'source': 'منبع ترافیک',
        'medium': 'رسانه',
        'campaign': 'نام کمپین',
        'content?': 'اختیاری',
        'term?': 'اختیاری'
    }
}"""
UTM_PARAMS = {
    "UTM": {"source": "newsletter", "medium": "email", "campaign": "summer_sale_2025"}
}

CKEDITOR_5_FILE_UPLOAD_PATH = "about_media/"
CKEDITOR_5_IMAGE_BACKEND = "pillow"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "|",
            "link",
            "blockQuote",
            "codeBlock",
            "|",
            "numberedList",
            "bulletedList",
            "|",
            "indent",
            "outdent",
            "alignment",
            "|",
            "insertTable",
            "mediaEmbed",
            "imageUpload",
            "|",
            "undo",
            "redo",
        ],
        "language": "fa",
    }
}


# default settings (optional)
JALALI_DATE_DEFAULTS = {
    # if change it to true then all dates of the list_display will convert to the Jalali.
    "LIST_DISPLAY_AUTO_CONVERT": False,
    "Strftime": {
        "date": "%y/%m/%d",
        "datetime": "%H:%M:%S _ %y/%m/%d",
    },
    "Static": {
        "js": [
            "admin/js/django_jalali.min.js",
        ],
        "css": {
            "all": [
                "admin/css/django_jalali.min.css",
            ]
        },
    },
}

# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# SECURE_HSTS_SECONDS = 0
# SECURE_HSTS_INCLUDE_SUBDOMAINS = False
# SECURE_HSTS_PRELOAD = False

# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_DOMAIN = '.abajstore.ir'


# CSRF_COOKIE_DOMAIN = '.abajstore.ir'
# CSRF_TRUSTED_ORIGINS = ['https://abajstore.ir', 'https://www.abajstore.ir',
#                         'http://abajstore.ir', 'http://www.abajstore.ir',
#                         'https://pec.shaparak.ir', 'https://www.pec.shaparak.ir']

# CORS_ALLOWED_ORIGINS = [
#     "https://abajstore.ir",
#     "http://abajstore.ir",
#     "https://www.abajstore.ir",
#     "http://www.abajstore.ir",
#     "http://localhost:8000",
#     "https://pec.shaparak.ir",
#     "https://www.pec.shaparak.ir"
# ]
# CORS_ALLOW_CREDENTIALS = True
