# Generated by Django 5.1.6 on 2026-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="مبلغ پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="authority_id",
            field=models.CharField(max_length=255, verbose_name="شناسه اعتبار پرداخت"),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="ref_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="شناسه مرجع پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="response_code",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="کد پاسخ درگاه"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="response_json",
            field=models.JSONField(default=dict, verbose_name="اطلاعات پاسخ درگاه"),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "در انتظار پرداخت"),
                    (2, "پرداخت موفق"),
                    (3, "پرداخت ناموفق"),
                ],
                default=1,
                verbose_name="وضعیت پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
            ),
        ),
    ]
