# Generated by Django 5.1.6 on 2026-08-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0001_initial"),
        ("Products", "0030_products_discount_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitemmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم\u200cهای سبد خرید",
            },
        ),
        migrations.AlterModelOptions(
            name="cartmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبدهای خرید",
            },
        ),
        migrations.AlterField(
            model_name="cartitemmodel",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="Cart.cartmodel",
                verbose_name="سبد خرید",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemmodel",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="cartitemmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="Products.products",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="cartitemmodel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="cartmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
