# Generated by Django 5.1.6 on 2026-08-14 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashbord", "0007_remove_address_receiver_name_address_first_name_and_more"),
        ("Products", "0030_products_discount_percent"),
        ("order", "0001_initial"),
        (
            "pyment",
            "0002_alter_paymentmodel_options_alter_paymentmodel_amount_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couponmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitemmodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
        migrations.AlterModelOptions(
            name="ordermodel",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="code",
            field=models.CharField(max_length=100, verbose_name="کد تخفیف"),
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="discount_percent",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="درصد تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ انقضا"
            ),
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="max_limit_usage",
            field=models.PositiveIntegerField(
                default=10, verbose_name="حداکثر تعداد استفاده"
            ),
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="couponmodel",
            name="used_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="coupon_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="استفاده\u200cکنندگان",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="order.ordermodel",
                verbose_name="سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.products",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Dashbord.address",
                verbose_name="آدرس ارسال",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="order.couponmodel",
                verbose_name="کد تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ ثبت سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pyment.paymentmodel",
                verbose_name="پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "در انتظار پرداخت"),
                    (2, "موفقیت\u200cآمیز"),
                    (5, "لغو شده"),
                ],
                default=1,
                verbose_name="وضعیت سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="مبلغ کل",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ آخرین بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
