# Generated by Django 5.1.6 on 2026-07-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0025_products_discounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image",
                verbose_name=" بارگذاری تصویر اصلی",
            ),
        ),
    ]
