# Generated by Django 5.1.6 on 2026-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0026_brand_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image/brand",
                verbose_name=" بارگذاری تصویر",
            ),
        ),
    ]
