# Generated by Django 5.1.6 on 2026-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0027_alter_brand_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="specialized_review",
            field=models.TextField(blank=True, null=True, verbose_name="بررسی تخصصی"),
        ),
        migrations.AddField(
            model_name="products",
            name="specialized_review_image",
            field=models.TextField(
                blank=True, null=True, verbose_name="بررسی تخصصی عکس برای قسمت"
            ),
        ),
    ]
