# Generated by Django 5.1.6 on 2026-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0028_products_specialized_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="specialized_review_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image",
                verbose_name="بررسی تخصصی عکس برای قسمت",
            ),
        ),
    ]
