# Generated by Django 5.1.6 on 2026-08-05 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0029_alter_products_specialized_review_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="discount_percent",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
